[package]
name = "multiway-tug"
version = "0.1.0"
authors = ["Corey Richardson <cmr@o1labs.org>"]
edition = "2018"

[dependencies]
rand = "0.7"
smallvec = "0.6"
tui = "0.6"
termion = "1.5"
failure = "*"